// basic functions
#define BIOS_SOFTRESET 0x00
#define BIOS_HALT 0x06
#define BIOS_ARM7_SLEEP 0x07
#define BIOS_INTRWAIT 0x04
#define BIOS_VBLANKINTRWAIT 0x05
#define BIOS_DIV 0x09
#define BIOS_SQRT 0x0d
#define BIOS_CPUSET 0x0b
#define BIOS_CPUSETFAST 0x0c

// decompression functions
#define BIOS_BITUNPACK 0x10
#define BIOS_LZ77UNCOMPREADNORMALWRITE8BIT 0x11
#define BIOS_DSI_LZ77UNCOMPREADBYCALLBACKWRITE8BIT 0x01
#define BIOS_DSI_LZ77UNCOMPREADBYCALLBACKWRITE16BIT 0x02
#define BIOS_NDS_LZ77UNCOMPREADBYCALLBACKWRITE16BIT 0x12
#define BIOS_HUFFUNCOMPREADBYCALLBACK 0x13
#define BIOS_RLUNCOMPREADNORMALWRITE8BIT 0x14
#define BIOS_RLUNCOMPREADBYCALLBACKWRITE16BIT 0x15
#define BIOS_ARM9_DIFF8BITUNFILTERWRITE8BIT 0x16
#define BIOS_ARM9_DIFF8BITUNFILTERWRITE16BIT 0x18

// sound
#define BIOS_ARM7_SOUNDBIAS 0x08
#define BIOS_ARM7_CUSTOMHALT 0x1f

// new nds functions
#define BIOS_WAITBYLOOP 0x03
#define BIOS_GETCRC16 0x0e
#define BIOS_NDS_ISDEBUGGER 0x0f
#define BIOS_ARM7_GETSINETABLE 0x1a
#define BIOS_NDS7_GETPITCHTABLE 0x1b
#define BIOS_ARM7_GETVOLUMETABLE 0x1c
#define BIOS_ARM7_GETVOLUMEPROCS 0x1d
#define BIOS_ARM9_CUSTOMPOST 0x1f

// new dsi functions
#define BIOS_DSI_RSA_INIT_CRYPTO_HEAP 0x20
#define BIOS_DSI_RSA_DECRYPT 0x21
#define BIOS_DSI_RSA_DECRYPT_UNPAD 0x22
#define BIOS_DSI_RSA_DECRYPT_OPENGPG_SHA1 0x23
#define BIOS_DSI_SHA1_INIT 0x24
#define BIOS_BSI_SHA1_UPDATE 0x25
#define BIOS_DSI_SHA1_FINISH 0x26
#define BIOS_DSI_SHA1_INIT_UPDATE_FIN 0x27
#define BIOS_SHA1_COMPARE_20_BYTES 0x28
#define BIOS_SHA1_RANDOM_MAYBE 0x29
